### PR TITLE
Add fl history

### PR DESCRIPTION
**Pull request by marwahaha**
two options here:
Option 1:
```
kmarwaha-m01:fl kmarwaha$ fl history

pandu
--------
2018-03-21  blah
2018-03-21  singing
2018-03-18  talking about life

pandu-2
----
2018-03-19  talking about life

pandu-3
------
2018-03-20  talk about stuff

pandu-4
-----------------
2018-03-20  ok

pandu-5
-----
2018-03-21  singing
kmarwaha-m01:fl kmarwaha$ fl history pandu

pandu
--------
2018-03-21  blah
2018-03-21  singing
2018-03-18  talking about life
```

Option 2:
```
kmarwaha-m01:fl kmarwaha$ fl history
++++++++++++++++++++++++++++++
pandu
------------------------------
2018-03-21  blah
2018-03-21  singing
2018-03-18  talking about life
++++++++++++++++++++++++++++++
pandu-2
------------------------------
2018-03-19  talking about life
++++++++++++++++++++++++++++++
pandu-3
------------------------------
2018-03-20  talk about stuff
++++++++++++++++++++++++++++++
pandu-4
------------------------------
2018-03-20  ok
++++++++++++++++++++++++++++++
pandu-5
------------------------------
2018-03-21  singing
kmarwaha-m01:fl kmarwaha$ fl history pandu
++++++++++++++++++++++++++++++
pandu
------------------------------
2018-03-21  blah
2018-03-21  singing
2018-03-18  talking about life
```
(i could get a final +++ row to print out, too...)

### CODE REVIEW

**Comment by prendradjaja** [comment]
Only glanced at this thus far.

I think `history` without a user should be completely chronological (as opposed to grouping by user first, then chronological), no?

**Comment by prendradjaja** [comment]
^ I might add an option or something for this later. But for now I'll merge.

**Comment by marwahaha** [comment]
can you make a ticket about it?

**Comment by prendradjaja** [comment]
Added.

**Pull request merged**
