### PR TITLE
Pretty print to database

### PR DESCRIPTION
**Pull request by prendradjaja**
```
Instead of

  [{"user":"kunal", ...}, {"user":"pandu", ...}]

do this:

  [
    {
      "user":"kunal",
      ...
    },
    {
      "user":"pandu",
      ...
    }
  ]

This is more diffable, human-readable and editable.
```

### CODE REVIEW

**Comment by prendradjaja** [comment]
I think next time I have a sesh like this (opening multiple PRs one after another...) I kinda want to batch them all into one PR. This is easier to deal with *and* prevents us from having to deal with potential merge conflicts later if my PRs conflict with each another.

However, that does make for a messier git history on master. What do you think of changing to merge commits (instead of squash and merge)? That would require a little more discipline in cleaning up (`git rebase -i`) history before making PRs -- that is, assuming we want a clean git history on master.

**Comment by marwahaha** [comment]
1. you can add me as a reviewer instead of assigning it to me! to me the intent is more clear.
2. I prefer squash merging because I don't trust my own discipline ;) Also, multiple PRs forces each distinct change to be reviewed & discussed separately (i.e. no "riders")
3. i'm mixed about this PR. on what scale is this inefficient? perhaps, we shouldn't edit the data directly anyways.

**Comment by prendradjaja** [comment]
1. what's the difference between reviewer and assignee?
2. fair enough
3. on a scale much larger than we'll reach for the time being. i think by the time we reach that point, we will hopefully have migrated to a proper database anyway (?). as for editing data directly: i suppose if we make it harder to edit directly, then that encourages us to write good features. at the same time, though, i think the primary aim is still to make a useful tool -- and this increases the usefulness of the tool.

**Comment by prendradjaja** [comment]
Added configurability.

**Comment by prendradjaja** [comment]
Thanks! Do you like to delete feature branches after merging? It's what I'm used to, and I think it makes sense.

**Pull request merged**
